import $ from "jquery";
export let dict = {
     Dictionary:{
    en:{
        'Vladislav Vorobyev':'Vladislav Vorobyev',
        'Front-end developer': 'Front-end developer',
        'My Skills': 'My Skills',
        'About me' :'About me',
        'AboutText': 'When I first saw in the browser the inscription "Hello World", from this moment it all started.',
        'inSocial': 'Оn the web',
       'Perseverance': 'Perseverance',
        'Purposefulness':'Purposefulness',
        'Aresponsibility': 'A responsibility',
        'Sociability': 'Sociability',
        'SkillTeam':'Skill to work in team',
        'Adapt':' Quickly adapt in new conditions',
        'Education': 'Education',
        /////////////////////////////////////////////////
        'My story':'My story',
        'First step':'First step',
        'First step_text': "At the beginning of 2016,  I've started started to learn programming languages of web design.Markup language HTML page and the formal language of CSS.",
        'First course':'First course',
        "First course _text":"In the autumn of 2017 I took courses from EPAM on Front End, during the training I had to solve different types of problems, I was also introduced to the methodology of BEM and grid layout technology. It was my first layout project.",
        "RS School": "RS School",
        "RS School_text":"In spring of 2018 I started training at the Rolling Scopes School and got a lot of useful experience. I also completed my first marcup-1 project at these courses.",
        "Some of them examples works": "Some of them examples works",
        "Professional skill": "Professional skill",
        'EEC&T':'The first higher education',
        "EEC&T_text": "He graduated from the Belarusian - Russian universitstvt and received a higher education in the field of preparation of electrical equipment of cars.",
        "Master's Courses": "Master's Courses",
        "Master's Courses_text":"In March 2018 he graduated from the magistracy and received a master's degree in the direction of Energy.",
        "Master's Courses 2.0": "Master's Courses 2.0",
        "Master's Courses 2.0_text":'In July I enter the magistracy in the specialty: System analysis.',
        'Contact information':'Contact information',
        "Belarus": "Belarus",
        "Mogilev": "Mogilev",
        /////////////////////////////////////////////////main
        "The beginner of the front-end development": "The beginner of the front-end development",
        "Main": "Main",
        "Framework": "Framework",
        "Skills": "Skills",
        "Story": "Story",
        "Feedback": "Feedback",
        ///////////////////////////////////////////////2st_slide
        "My favorite framework":"My favorite framework is React.I work with it more than one year.Most of my projects are created by using React",
        "Skills of working with the githab": "Skills of working with the githab",
        "Adaptive site layout": "Adaptive site layout",
        "Willingness to work as a team":"Willingness to work as a team",
        "Web development methodology is BEM": "Web development methodology is BEM",
        ///////////////////////////////////////////////Slider
        'Slider_1st Slide':'Нey there! My name is Vlad and I am constantly improving in the field of web development. From the beginning - it was the middle of 2016- it have been written a lot lines of code. I try not to miss new opportunities and not to forget the basics.',
        "Slider_2wo Slide": 'I am well in adapting to new conditions. During the training courses we were taught to work in a team and be able to work on one project.',
        "Slider_3th Slide-main": 'Main skills',
        "Slider_errorMessage": 'Not so fast',
    },
    ru: {
        'Vladislav Vorobyev':'Владислав Воробьёв',
        'Front-end developer':'Веб разработчик',
        'My Skills': 'Личные качества',
        'About me': 'О себе',
        'AboutText': 'Когда я впервые увидел в окне браузера надпись "Hello World",с этого момента все и началось.',
        'inSocial': 'В сети',
        'Perseverance':'Настойчивость',
        'Purposefulness':'Целеустремленность',
        'Aresponsibility':'Отвественность',
        'Sociability':'Коммуникабельность',
        'SkillTeam':'Умение работать в команде',
        'Adapt':' Быстро адаптироваться в новых условиях',
        'Education':'Образование',
        /////////////////////////////////////////////////
        'My story': 'Моя история',
        'First step': 'Первые шаги',
        'First step_text': "В начале 2016 года, я начал изучать языки программирования веб  дизайна.Язык разметки HTML и формальный язык CSS",
        'First course': 'Первые курсы',
        "First course _text": "Осенью 2017 года я проходил курсы EPAM на Front End, во время тренинга мне приходилось решать различные типы проблем, меня также познакомили с методологией технологии BEM и сеточной верстки. Это был мой первый проект макета.",
        "RS School": "RS School",
        "RS School_text": "Весной 2018 года я начал обучение в Школе Rolling Scopes и получил много полезного опыта.На этих курсах я также завершил свой первый проект marcup-1.",
        "Some of them examples works": "Некоторые из примерных работ",
        "Professional skill": "Прикладные навыки",
         'EEC&T': 'Первое высшее образование',
        "EEC&T_text":"Окончил белорусско-российский универсвитет  и получил высшеее образование по направлению подготовки Электрооборудование автомобилей.",
        "Master's Courses": "Магистратура",
        "Master's Courses_text": 'В марте 2018 года он окончил магистратуру и получил степень магистра в области энергетики.',
        "Master's Courses 2.0":"Магистратура 2.0",
        "Master's Courses 2.0_text":"В июле поступаю в магистратуру по специальности:Cистемный анализ.",
        'Contact information': 'Контактная информация',
        "Belarus": "Беларусь",
        "Mogilev": "Могилев",
        //////////////////////////////////////////////////////////////////////////////main
        "The beginner of the front-end development": "Начинающий веб разработчик",
        "Main": "Главная",
        "Framework": "Фреймворк",
        "Skills": "Умения",
        "Feedback": "Связаться",
        //////////////////////////////////////////////////////////////////////////////2st_slide
        "My favorite framework": "Мой основной фреймворк-React.Я работаю с ним не один год.Большинство моих проектов создаются с помощью React",
        "Skills of working with the githab": "Опыт работы с Githab",
        "Adaptive site layout":"Адаптивная верстка",
        "Willingness to work as a team":"Умение работать в команде",
        "Web development methodology is BEM":"Верстка по методологии БЭМ",
         ///////////////////////////////////////////////Slider
        'Slider_1st Slide': 'Всем привет !Меня зовут Влад и я постоянно развиваюсь в сфере web разработки.Со своего начала - это была середина 2016г - было написано немало строк кода. Я стараюсь не упускать новые фичи и при этом не забывать основы.',
        "Slider_2wo Slide":'Я хорошо умею адаптироваться в новых условиях, во время обучения на курсах нас учили работать в команде и уметь работать  над одним проектом.',
        "Slider_3th Slide-main":'Основные навыки',
        "Slider_errorMessage":'Тише...'
    }
},
     


};
